/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ChatMessage } from '../models/chat-message';
import { findChatMessages } from '../fn/messages/find-chat-messages';
import { FindChatMessages$Params } from '../fn/messages/find-chat-messages';

@Injectable({ providedIn: 'root' })
export class MessagesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findChatMessages()` */
  static readonly FindChatMessagesPath = '/chat-messages/messages/{senderId}/{recipientId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findChatMessages()` instead.
   *
   * This method doesn't expect any request body.
   */
  findChatMessages$Response(params: FindChatMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatMessage>>> {
    return findChatMessages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findChatMessages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findChatMessages(params: FindChatMessages$Params, context?: HttpContext): Observable<Array<ChatMessage>> {
    return this.findChatMessages$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ChatMessage>>): Array<ChatMessage> => r.body)
    );
  }

}
