/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CocktailResponse } from '../models/cocktail-response';
export interface PageResponseCocktailResponse {
  content?: Array<CocktailResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
