/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatMessage } from '../../models/chat-message';

export interface FindChatMessages$Params {
  senderId: string;
  recipientId: string;
}

export function findChatMessages(http: HttpClient, rootUrl: string, params: FindChatMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatMessage>>> {
  const rb = new RequestBuilder(rootUrl, findChatMessages.PATH, 'get');
  if (params) {
    rb.path('senderId', params.senderId, {});
    rb.path('recipientId', params.recipientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ChatMessage>>;
    })
  );
}

findChatMessages.PATH = '/chat-messages/messages/{senderId}/{recipientId}';
